# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e54261ab42023add8a1203eaa7104376751262e8718ebefcb3c8123e6eec23a195aaa629a29218c09c54ef45b06ab5ebc0e7856348f01adbf07955e7412744

test:
  secret_key_base: 4c622f75aaec8fe8fe16d5d3cca3ba781c414d9f75a9a93985845773c0e0f6dea0a35a302352c59781099b952aa29e22433afcbcc53e795336d7708da0a4c362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
